dofile(minetest.get_modpath('aether2') .. '/nodes.lua')
dofile(minetest.get_modpath('aether2') .. '/tools.lua')
dofile(minetest.get_modpath('aether2') .. '/crafting.lua')
dofile(minetest.get_modpath('aether2') .. '/craft_items.lua')
dofile(minetest.get_modpath('aether2') .. '/weapons.lua')
dofile(minetest.get_modpath('aether2') .. '/worldgen.lua')
dofile(minetest.get_modpath('aether2') .. '/portal.lua')
